//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITS.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public class Attachment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attachment()
        {
            this.AttachmentChanges = new HashSet<AttachmentChange>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] BinaryData { get; set; }
        public long Size { get; set; }
        public string FileType { get; set; }
        public int? IssueId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttachmentChange> AttachmentChanges { get; set; }
        public virtual Issue Issue { get; set; }
    }
}
