//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/*
VALID TYPES OF CHANGES:
CREATION
MODIFICATION
 */ 
namespace ITS.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public class CommentChange : BaseChange
    {
        public int CommentId { get; set; }
        public string NewValue { get; set; }
    
        public virtual Comment Comment { get; set; }
    }
}
